### ISSUE TITLE
Translation for other language is not working

### ISSUE THREAD

**Issue by Deeptimay** [Ra-Na/GTranslate-strings-xml#1]
This script is working fine for language "ja" . But for languages like "kn" , "hi" it's generating random numbers. please help. 
Thanks in adv.

**Comment by Ra-Na** [comment]
Fixed it, please test.

**Comment by Deeptimay** [comment]
Thanks bro. It's working beautifully.

**Comment by Deeptimay** [comment]
Hi, by mistake I had checked for "ka", which is working f9. 
But I wanted for "kn" and "te" characters which is not working. Please help.

**Comment by Ra-Na** [comment]
Hey, I checked your issue. KO and JP work, for TE and KN I get character mess. However, this character mess is because the console font cannot display the characters. If I copy-paste the character mess into google translate with the setting "detect language" then google translate recognizes the language (Teluga) and gives the correct back-translation. So the real issue is that the systems we use cannot display the characters. If you install support for the Teluga and Kannada language on your system, the fonts should be viewed correctly. That means even if you copy the character mess to your android resource file, android should display the fonts correctly, supposing that the fonts are included in the android system. So: Try to install font support on your system and check whether android can view the translations, even when our systems don't have font support for Teluga and Kannada.

**Comment by Ra-Na** [comment]
OK, doing

sudo apt-get install fonts-indic

on my system + reboot shows the fonts correctly.

**Comment by Deeptimay** [comment]
YES, It's working. 
Thanks.
